name: jake-tools
main: index.js
version: 0.0.10
description: 辅助快速编写 Jakefiles
author:
  name: 清笃
  email: qingdu@alibaba-inc.com
engines:
  node: >=0.6.0
os:
  - !win32
homepage: http://gitlab.taobao.ali.com/jaketools
repository:
  type: git
  url: git@gitlab.alibaba-inc.com:jaketools.git
bugs:
  url: http://gitlab.taobao.ali.com/jaketools/issues
dependencies:
  stylus: >=0.29.0
  glob: >=3.1.0
  jade: >=0.27.0
  underscore: >=1.3.0
  request: >=2.11.0
  coffee-script: >= 1.3.0
  mkdirp: >=0.3.0
  mocha: >=1.6.0
  jscover: >=0.1.1
  # uglify-js: >=1.3.0
  yamljs: >=0.1.3
scripts:
  prepublish: make all
  postpublish: make clean
